controller_manager:
  ros__parameters:
    update_rate: 10  # Hz
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    platform_velocity_controller:
      type: diff_drive_controller/DiffDriveController

platform_velocity_controller:
  ros__parameters:
    cmd_vel_topic: "/cmd_vel"
    left_wheel_names: ["left_wheel_joint"]
    right_wheel_names: ["right_wheel_joint"]

    wheel_separation: 0.3  # Distance between the wheels (0.15m left + 0.15m right)
    wheel_radius: 0.1      # Radius of the wheels (matches the URDF)

    wheel_separation_multiplier: 1.0
    left_wheel_radius_multiplier: 1.0
    right_wheel_radius_multiplier: 1.0

    publish_rate: 50.0  # Match to CoppeliaSim simulation step frequency
    odom_frame_id: odom
    base_frame_id: base_link  # Matches the URDF base link name
    pose_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]
    twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]

    open_loop: true  # Use true for simulation without feedback
    enable_odom_tf: true  # Publish transform between odom and base_frame

    cmd_vel_timeout: 0.5

    # Velocity and acceleration limits
    linear.x.has_velocity_limits: true
    linear.x.has_acceleration_limits: true
    linear.x.has_jerk_limits: false
    linear.x.max_velocity: 1.0
    linear.x.min_velocity: -1.0
    linear.x.max_acceleration: 1.0

    angular.z.has_velocity_limits: true
    angular.z.has_acceleration_limits: true
    angular.z.has_jerk_limits: false
    angular.z.max_velocity: 1.0
    angular.z.min_velocity: -1.0
    angular.z.max_acceleration: 1.0
